// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../react

import { ReactNode } from 'react';

type Size = 'oneThird' | 'oneHalf' | 'twoThirds';
export interface CardColumn {
    component: ReactNode;
    size?: Size;
    bg?: any;
    flush?: boolean;
}
export interface TwoColumnCardProps {
    left: CardColumn;
    right: CardColumn;
}
export function TwoColumnCard(props: TwoColumnCardProps): import("react/jsx-runtime").JSX.Element;
export {};

interface HookParameters {
    perPage?: number;
    start?: number;
}
interface Cursor {
    first?: number;
    last?: number;
    after?: any;
    before?: any;
}
type HookGenerator = (cursor: Cursor) => any;
export function usePaginateController(generator: HookGenerator, parameters?: HookParameters): any[];
export {};

